#requires -Version 7
#
# A wizard - walks a human through a manual procedure step by step.
# Generated by the /wizard skill. Windows-native counterpart to template.sh.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# Wizard library - delightful, consistent UX. Identical across every wizard.
# ---------------------------------------------------------------------------

# Author sets these at the top of the stages section.
$script:TOTAL_STAGES = 0
$script:REQUIRE_ADMIN = $false

$script:StageIndex    = 0
$script:EnvFile       = if ($env:ENV_FILE) { $env:ENV_FILE } else { '.env' }
$script:WrittenEnv    = [System.Collections.Generic.List[string]]::new()
$script:WrittenSecret = [System.Collections.Generic.List[string]]::new()
$script:Skipped       = [System.Collections.Generic.List[string]]::new()
$script:Failed        = [System.Collections.Generic.List[string]]::new()

function Test-Admin {
  ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
  ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

# Assert-Elevation - relaunch once, elevated, if the wizard needs admin rights.
# One elevation prompt for the whole run; never one per stage.
function Assert-Elevation {
  if (-not $script:REQUIRE_ADMIN -or (Test-Admin)) { return }
  Write-Host '  This wizard needs administrator rights - relaunching elevated...' -ForegroundColor Yellow
  Start-Process pwsh -Verb RunAs -ArgumentList @(
    '-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $PSCommandPath
  )
  exit 0
}

function Clear-Screen { if ($Host.UI.RawUI) { try { Clear-Host } catch { } } }

# Banner "Title" - opening frame: what this wizard does.
function Banner([string]$Title) {
  Clear-Screen
  Write-Host ''
  Write-Host "  $Title" -ForegroundColor Blue
  Write-Host "  $($script:TOTAL_STAGES) stages" -ForegroundColor DarkGray
  Write-Host ''
  Write-Host '  You drive the browser; this wizard tells you exactly what to do and' -ForegroundColor DarkGray
  Write-Host '  captures the values you copy back. Stop any time with Ctrl-C and re-run' -ForegroundColor DarkGray
  Write-Host '  later - it remembers values already saved.' -ForegroundColor DarkGray
  Write-Host ''
  Wait-Step 'Ready to start?'
}

function Say ([string]$Text) { Write-Host "  $Text" }
function Step([string]$Text) { Write-Host '  * ' -ForegroundColor Blue -NoNewline; Write-Host $Text }
function Note([string]$Text) { Write-Host "  $Text" -ForegroundColor DarkGray }
function Warn([string]$Text) { Write-Host "  ! $Text" -ForegroundColor Yellow }
function Ok  ([string]$Text) { Write-Host "  + $Text" -ForegroundColor Green }

# Stage "Name" { ... } - clear the screen, announce progress, run the body.
# The body is wrapped in try/catch so one failing stage never aborts the run;
# the failure is recorded and shown in the closing summary.
function Stage {
  param([Parameter(Mandatory)][string]$Name, [Parameter(Mandatory)][scriptblock]$Body)
  Clear-Screen
  $script:StageIndex++
  Write-Host ''
  Write-Host "  > Stage $($script:StageIndex)/$($script:TOTAL_STAGES) - $Name" -ForegroundColor Blue
  Write-Host ''
  try { & $Body }
  catch {
    Warn "stage '$Name' failed: $($_.Exception.Message)"
    $script:Failed.Add("$Name - $($_.Exception.Message)")
    Wait-Step 'Press Enter to continue with the next stage'
  }
}

# Open-Url URL - open in the human's default browser.
function Open-Url([string]$Url) {
  Write-Host '  ^ opening ' -ForegroundColor Green -NoNewline; Write-Host $Url
  try { Start-Process $Url | Out-Null }
  catch { Warn "couldn't open a browser - visit it manually: $Url" }
}

# Wait-Step "msg" - wait for the human to confirm they've done the manual part.
function Wait-Step([string]$Message = 'Press Enter to continue') {
  Write-Host "  $Message " -ForegroundColor DarkGray -NoNewline
  Read-Host | Out-Null
}

# Confirm-Step "question" - y/N gate; returns $true on yes.
function Confirm-Step([string]$Question) {
  Write-Host "  ? $Question [y/N] " -ForegroundColor Yellow -NoNewline
  (Read-Host) -match '^[Yy]'
}

# Get-ExistingEnv KEY - current value of KEY in the env file, if any.
function Get-ExistingEnv([string]$Key) {
  if (-not (Test-Path $script:EnvFile)) { return $null }
  $line = Get-Content $script:EnvFile | Where-Object { $_ -match "^$([regex]::Escape($Key))=" } | Select-Object -Last 1
  if ($line) { return $line.Substring($line.IndexOf('=') + 1) }
  $null
}

# Ask KEY "Prompt" - read a visible value. Enter keeps the existing .env value.
function Ask([string]$Key, [string]$Prompt) {
  $current = Get-ExistingEnv $Key
  $suffix  = if ($current) { ' [Enter keeps current]' } else { '' }
  Write-Host "  $Prompt$suffix " -NoNewline
  $answer = Read-Host
  if (-not $answer -and $current) { $answer = $current }
  Set-Variable -Name $Key -Value $answer -Scope Script
  $answer
}

# Ask-Secret KEY "Prompt" - like Ask, but input is hidden.
function Ask-Secret([string]$Key, [string]$Prompt) {
  $current = Get-ExistingEnv $Key
  $suffix  = if ($current) { ' [Enter keeps current]' } else { '' }
  $secure  = Read-Host "  $Prompt$suffix" -AsSecureString
  $value   = [System.Net.NetworkCredential]::new('', $secure).Password
  if (-not $value -and $current) { $value = $current }
  Set-Variable -Name $Key -Value $value -Scope Script
  $value
}

# Write-Env KEY VALUE - upsert KEY=VALUE into the env file. Idempotent.
# Writes UTF-8 without BOM so dotenv parsers don't choke on the first key.
function Write-Env([string]$Key, [string]$Value) {
  $path = if ([System.IO.Path]::IsPathRooted($script:EnvFile)) { $script:EnvFile }
          else { Join-Path $PWD $script:EnvFile }
  $lines = if (Test-Path $path) {
    @(Get-Content $path | Where-Object { $_ -notmatch "^$([regex]::Escape($Key))=" })
  } else { @() }
  $lines += "$Key=$Value"
  [System.IO.File]::WriteAllLines($path, $lines, (New-Object System.Text.UTF8Encoding $false))
  $script:WrittenEnv.Add($Key)
  Ok "wrote $Key -> $($script:EnvFile)"
}

# Test-Gh - is the gh CLI present and authenticated?
function Test-Gh {
  if (-not (Get-Command gh -ErrorAction SilentlyContinue)) { return $false }
  gh auth status 2>$null | Out-Null
  $LASTEXITCODE -eq 0
}

# Set-Secret NAME VALUE - set a GitHub Actions repo secret via gh.
function Set-Secret([string]$Name, [string]$Value) {
  if (Test-Gh) {
    $Value | gh secret set $Name 2>$null | Out-Null
    if ($LASTEXITCODE -eq 0) { $script:WrittenSecret.Add($Name); Ok "set GitHub secret $Name"; return }
  }
  $script:Skipped.Add("GitHub secret $Name (set it manually: gh secret set $Name)")
  Warn "skipped GitHub secret $Name - gh not ready; set it later"
}

# Set-Var NAME VALUE - set a GitHub Actions repo variable (non-secret).
function Set-Var([string]$Name, [string]$Value) {
  if (Test-Gh) {
    gh variable set $Name --body $Value 2>$null | Out-Null
    if ($LASTEXITCODE -eq 0) { Ok "set GitHub variable $Name"; return }
  }
  $script:Skipped.Add("GitHub variable $Name")
  Warn "skipped GitHub variable $Name - gh not ready; set it later"
}

# Finish - closing summary table, then hold the window open.
function Finish {
  Clear-Screen
  Write-Host ''
  Write-Host '  Setup complete' -ForegroundColor Green
  Write-Host ''
  $rows = @()
  $rows += [pscustomobject]@{ Result = 'env values written'; Count = $script:WrittenEnv.Count;    Detail = ($script:WrittenEnv    -join ', ') }
  $rows += [pscustomobject]@{ Result = 'secrets set';        Count = $script:WrittenSecret.Count; Detail = ($script:WrittenSecret -join ', ') }
  $rows += [pscustomobject]@{ Result = 'skipped';            Count = $script:Skipped.Count;       Detail = ($script:Skipped       -join '; ') }
  $rows += [pscustomobject]@{ Result = 'failed stages';      Count = $script:Failed.Count;        Detail = ($script:Failed        -join '; ') }
  $rows | Format-Table -AutoSize -Wrap | Out-String | Write-Host
  if ($script:Failed.Count) { Warn 'some stages failed - see the table above' }
  Write-Host ''
  Read-Host '  Press Enter to close' | Out-Null
}

# ---------------------------------------------------------------------------
# STAGES - author this section. One Stage per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# Set REQUIRE_ADMIN = $true if any stage needs administrator rights.
# ---------------------------------------------------------------------------

$script:TOTAL_STAGES  = 1
$script:REQUIRE_ADMIN = $false

Assert-Elevation
Banner 'Stripe setup'

# -- Example stage: replace with your real steps ---------------------------
Stage 'Stripe - API keys' {
  Say "We'll grab your Stripe test keys and store them for local dev + CI."
  Open-Url 'https://dashboard.stripe.com/test/apikeys'
  Step 'On the API keys page, copy the Publishable key (starts pk_test_).'
  $pub = Ask 'STRIPE_PUBLISHABLE_KEY' 'Paste the publishable key:'
  Step "Click 'Reveal test key' on the Secret key row, then copy it."
  $sec = Ask-Secret 'STRIPE_SECRET_KEY' 'Paste the secret key:'
  Write-Env 'STRIPE_PUBLISHABLE_KEY' $pub
  Write-Env 'STRIPE_SECRET_KEY' $sec
  Set-Secret 'STRIPE_SECRET_KEY' $sec   # CI needs this one
}
# ---------------------------------------------------------------------------

Finish
